version: '3.8'

# 네트워크 tobias-network 생성



services:

  app:
    image: imkunyoung/discoveryservice
    container_name: discoveryservice
    ports:
      - 8761:8761
    volumes:
      - /app
    networks:
      - tobias-network

  app2:
    image: imkunyoung/gatewayservice_client:1.0
    container_name: gatewayservice_client
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
    ports:
      - 8000:8000
      - 80:80
    volumes:
      - /app2
    networks:
      - tobias-network

  app3:
    image: imkunyoung/gatewayservice_saler:1.0
    container_name: gatewayservice_saler
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
    ports:
      - 8001:8001
    volumes:
      - /app3
    networks:
      - tobias-network

  app4:
    image: imkunyoung/gatewayservice_manager:1.0
    container_name: gatewayservice_manager
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
    ports:
      - 8002:8002
    volumes:
      - /app4
    networks:
      - tobias-network

  app5:
    image: imkunyoung/configservice:1.0
    container_name: configservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
    ports:
      - 8888:8888
    volumes:
      - /app5
    networks:
      - tobias-network



  coupon-mariadb:
    image: mariadb:latest
    container_name: coupon-mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=couponservice
      - MYSQL_USER=couponservice
      - MYSQL_PASSWORD=1234
    #    ports:
    #      - 3306:3306
    volumes:
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    networks:
      - tobias-network

  app7:
    image: imkunyoung/couponservice:1.0
    container_name: couponservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
      - spring.datasource.url=jdbc:mariadb://coupon-mariadb:3306/couponservice?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
      - spring.datasource.username=couponservice
      - spring.datasource.password=1234
    depends_on:
      - coupon-mariadb
    #    ports:
    #      - 8003:8003
    volumes:
      - /app7
    networks:
      - tobias-network
  # mariadb
  #  app6:
  #    image: mariadb:10.5.8
  #    container_name: mariadb
  #    ports:
  #      - 3306:3306
  #    volumes:
  #      - /app6
  #    networks:
  #      - tobias-network
  #    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=bootuser
  #      - MYSQL_DATABASE=bootex
  #      - MYSQL_USER=bootuser


  app8:
    image: imkunyoung/pointservice:1.0
    container_name: pointservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb+srv://test:93414223@cluster0.3f1nxzq.mongodb.net/?retryWrites=true&w=majority
      - SPRING_DATA_MONGODB_DATABASE=mygrocerylist
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
  pointservice2-mongodb:
    image: mongo:4.4.15
    ports:
      - 27017:27017
    # volumes:
    #   - ~/volumes/jhipster/pointService2/mongodb/:/data/db/
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

networks:
  tobias-network:
    driver: bridge