version: '3.8'

# 네트워크 tobias-network 생성



services:

  app:
    image: imkunyoung/discoveryservice
    container_name: discoveryservice
    ports:
      - 8761:8761
    volumes:
      - /app
    networks:
      - tobias-network

  app2:
    image: imkunyoung/gatewayservice_client:1.0
    container_name: gatewayservice_client
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
    ports:
      - 8000:8000
      - 80:80
    volumes:
      - /app2
    networks:
      - tobias-network

  app3:
    image: imkunyoung/gatewayservice_saler:1.0
    container_name: gatewayservice_saler
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
    ports:
      - 8001:8001
    volumes:
      - /app3
    networks:
      - tobias-network

  app4:
    image: imkunyoung/gatewayservice_manager:1.0
    container_name: gatewayservice_manager
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
    ports:
      - 8002:8002
    volumes:
      - /app4
    networks:
      - tobias-network

  app5:
    image: imkunyoung/configservice:1.0
    container_name: configservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
    ports:
      - 8888:8888
    volumes:
      - /app5
    networks:
      - tobias-network



  coupon-mariadb:
    image: mariadb:latest
    container_name: coupon-mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=couponservice
      - MYSQL_USER=couponservice
      - MYSQL_PASSWORD=1234
    ports:
      - 3307:3307
    volumes:
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    networks:
      - tobias-network

  app7:
    image: imkunyoung/couponservice:1.0
    container_name: couponservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryservice:8761/eureka/
      - spring.datasource.url=jdbc:mariadb://coupon-mariadb:3307/couponservice?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
      - spring.datasource.username=couponservice
      - spring.datasource.password=1234
    depends_on:
      - coupon-mariadb
    ports:
      - 8003:8003
    volumes:
      - /app7
    networks:
      - tobias-network
# mariadb
#  app6:
#    image: mariadb:10.5.8
#    container_name: mariadb
#    ports:
#      - 3306:3306
#    volumes:
#      - /app6
#    networks:
#      - tobias-network
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    environment:
#      - MYSQL_ROOT_PASSWORD=bootuser
#      - MYSQL_DATABASE=bootex
#      - MYSQL_USER=bootuser


networks:
  tobias-network:
    driver: bridge