version: '3.8'

# mysql 컨테이너 생성하고 basketservice 컨테이너에 연결
services:
  basket-mysql:
    image: mysql:latest
    container_name: basket-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=basketservice
      - MYSQL_USER=basketservice
      - MYSQL_PASSWORD=1234
#    ports:
#      - 3306:3306
    volumes:
      - ~/docker/mysql/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/var/log/mysql:/var/log/mysql
    networks:
      - tobias-network

  app:
    image: imkunyoung/basketservice:1.0
    container_name: basketservice
    depends_on:
      - basket-mysql
    environment:
      - server.port=8003
      - spring.profiles.active=prod
      - spring.datasource.url=jdbc:mysql://basket-mysql:3306/basketservice?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
      - spring.datasource.username=basketservice
      - spring.datasource.password=1234
    ports:
      - 8003:8003
    volumes:
      - /app
    networks:
      - tobias-network

networks:
  tobias-network:
    driver: bridge